{
 "title": "Data Quality",
 "description": "One run - Full Pipeline View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "run_date",
    "query": "SELECT DISTINCT to_char(started_at::date, 'YYYY-MM-DD') AS run_date\nFROM raw.ingestion_run_log\nORDER BY run_date DESC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Full pipeline View",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n  i.run_id               AS ingestion_run_id,\r\n  i.started_at           AS ingestion_started_at,\r\n  i.status               AS ingestion_status,\r\n  i.duration_sec         AS ingestion_duration,\r\n  i.rows_movies_injected,\r\n  i.rows_ratings_injected,\r\n  i.rows_movies_total,\r\n  i.rows_ratings_total,\r\n\r\n  t.training_run_id,\r\n  t.training_started_at,\r\n  t.training_status,\r\n  t.training_duration,\r\n  t.training_error\r\n\r\nFROM raw.ingestion_run_log i\r\n\r\nLEFT JOIN LATERAL (\r\n    SELECT\r\n        run_id AS training_run_id,\r\n        started_at AS training_started_at,\r\n        status AS training_status,\r\n        duration_sec AS training_duration,\r\n        error_message AS training_error\r\n    FROM raw.training_run_log\r\n    WHERE started_at >= i.started_at\r\n      AND started_at < i.started_at + INTERVAL '2 hours'\r\n    ORDER BY started_at\r\n    LIMIT 1\r\n) t ON TRUE\r\n\r\nWHERE i.started_at >= '${run_date}'::date\r\n  AND i.started_at < ('${run_date}'::date + INTERVAL '1 day')\r\n\r\nORDER BY i.started_at DESC;"
    }
   ]
  },
  {
   "title": "Ingestions runs - raw_ratings_injected",
   "type": "barchart",
   "description": "Dernier run de la journée",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_run_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    rows_ratings_injected\r\n  FROM raw.ingestion_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_run_per_day\r\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Ingestions runs duration",
   "type": "barchart",
   "description": "Dernier run de la journée",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_run_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    duration_sec\r\n  FROM raw.ingestion_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_run_per_day\r\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Ingestions runs - raw_movies_injectd",
   "type": "barchart",
   "description": "Dernier run de la journée",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_run_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    rows_movies_injected\r\n  FROM raw.ingestion_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_run_per_day\r\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Training runs duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_training_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    duration_sec,\r\n    error_message\r\n  FROM raw.training_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_training_per_day\r\nORDER BY day DESC;"
    }
   ]
  }
 ]
}