{
 "title": "Data Drift",
 "description": "Initialisation d'un monitoring du data drift :\n- PSI mensuel des notes et des genres\n- note moyenne annuelle",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Drift mensuel des notes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n    period_value AS month,\r\n    metric_value\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'monthly'\r\n  AND metric_name = 'psi_rating_prev_month'\r\n  and metric_value>0\r\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Drift mensuel des genres",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n    period_value AS month,\r\n    metric_value\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'monthly'\r\n  AND metric_name = 'psi_genre_prev_month'\r\n  and metric_value>0\r\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Note moyenne annuelle",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT metric_value, period_value\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'yearly'\r\n  AND metric_name = 'avg_rating'\r\n  and metric_value>0\r\nORDER BY period_value asc\r\n;"
    }
   ]
  }
 ]
}