{
 "title": "KPI mensuels",
 "description": "Initialisation d'un suivi mensuel des notes, (nouveaux) noteurs et films notés sur les 3 dernières années",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Nb notes mensuelles par année",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_3_years AS (\r\n  SELECT DISTINCT split_part(period_value, '-', 1) AS year\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly' and metric_value>0\r\n  ORDER BY year DESC\r\n  LIMIT 3\r\n)\r\n\r\nSELECT\r\n  make_date(2000, split_part(m.period_value, '-', 2)::int, 1) AS time,\r\n  m.metric_value,\r\n  split_part(m.period_value, '-', 1) AS metric\r\nFROM raw.monitoring_metrics m\r\nJOIN last_3_years y\r\n  ON split_part(m.period_value, '-', 1) = y.year\r\nWHERE m.period_type = 'monthly'\r\n  AND m.metric_name = 'nb_notes'\r\n  AND m.metric_value > 0\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Notes moyennes mensuelles par année",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_3_years AS (\r\n  SELECT DISTINCT split_part(period_value, '-', 1) AS year\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly' and metric_value>0\r\n  ORDER BY year DESC\r\n  LIMIT 3\r\n),\r\nbase AS (\r\n  SELECT\r\n    to_char(to_date(period_value || '-01','YYYY-MM-DD'),'Mon') AS month,\r\n    split_part(period_value, '-', 1) AS year,\r\n    metric_value\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly'\r\n    AND metric_name = 'avg_rating'\r\n    AND metric_value > 0\r\n)\r\nSELECT\r\n  month,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 0 LIMIT 1) THEN metric_value END) AS y0,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 1 LIMIT 1) THEN metric_value END) AS y_1,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 2 LIMIT 1) THEN metric_value END) AS y_2\r\nFROM base\r\nGROUP BY month\r\nORDER BY MIN(to_date('2000-'||month||'-01','YYYY-Mon-DD'));"
    }
   ]
  },
  {
   "title": "Users mensuels par année",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_3_years AS (\r\n  SELECT DISTINCT split_part(period_value, '-', 1) AS year\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly' and metric_value>0\r\n  ORDER BY year DESC\r\n  LIMIT 3\r\n)\r\n\r\nSELECT\r\n  make_date(2000, split_part(m.period_value, '-', 2)::int, 1) AS time,\r\n  m.metric_value,\r\n  split_part(m.period_value, '-', 1) AS metric\r\nFROM raw.monitoring_metrics m\r\nJOIN last_3_years y\r\n  ON split_part(m.period_value, '-', 1) = y.year\r\nWHERE m.period_type = 'monthly'\r\n  AND m.metric_name = 'nb_users'\r\n  AND m.metric_value > 0\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "New users mensuels par année",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_3_years AS (\r\n  SELECT DISTINCT split_part(period_value, '-', 1) AS year\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly' and metric_value>0\r\n  ORDER BY year DESC\r\n  LIMIT 3\r\n),\r\nbase AS (\r\n  SELECT\r\n    to_char(to_date(period_value || '-01','YYYY-MM-DD'),'Mon') AS month,\r\n    split_part(period_value, '-', 1) AS year,\r\n    metric_value\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly'\r\n    AND metric_name = 'nb_new_users'\r\n    AND metric_value > 0\r\n)\r\nSELECT\r\n  month,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 0 LIMIT 1) THEN metric_value END) AS y0,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 1 LIMIT 1) THEN metric_value END) AS y_1,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 2 LIMIT 1) THEN metric_value END) AS y_2\r\nFROM base\r\nGROUP BY month\r\nORDER BY MIN(to_date('2000-'||month||'-01','YYYY-Mon-DD'));"
    }
   ]
  },
  {
   "title": "Movies mensuels par année",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_3_years AS (\r\n  SELECT DISTINCT split_part(period_value, '-', 1) AS year\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly' and metric_value>0\r\n  ORDER BY year DESC\r\n  LIMIT 3\r\n)\r\n\r\nSELECT\r\n  make_date(2000, split_part(m.period_value, '-', 2)::int, 1) AS time,\r\n  m.metric_value,\r\n  split_part(m.period_value, '-', 1) AS metric\r\nFROM raw.monitoring_metrics m\r\nJOIN last_3_years y\r\n  ON split_part(m.period_value, '-', 1) = y.year\r\nWHERE m.period_type = 'monthly'\r\n  AND m.metric_name = 'nb_movies'\r\n  AND m.metric_value > 0\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "New movies mensuelles par année",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_3_years AS (\r\n  SELECT DISTINCT split_part(period_value, '-', 1) AS year\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly' and metric_value>0\r\n  ORDER BY year DESC\r\n  LIMIT 3\r\n),\r\nbase AS (\r\n  SELECT\r\n    to_char(to_date(period_value || '-01','YYYY-MM-DD'),'Mon') AS month,\r\n    split_part(period_value, '-', 1) AS year,\r\n    metric_value\r\n  FROM raw.monitoring_metrics\r\n  WHERE period_type = 'monthly'\r\n    AND metric_name = 'nb_new_movies'\r\n    AND metric_value > 0\r\n)\r\nSELECT\r\n  month,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 0 LIMIT 1) THEN metric_value END) AS y0,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 1 LIMIT 1) THEN metric_value END) AS y_1,\r\n  MAX(CASE WHEN year = (SELECT year FROM last_3_years OFFSET 2 LIMIT 1) THEN metric_value END) AS y_2\r\nFROM base\r\nGROUP BY month\r\nORDER BY MIN(to_date('2000-'||month||'-01','YYYY-Mon-DD'));"
    }
   ]
  }
 ]
}