{
 "title": "KPI annuels",
 "description": "Initialisation d'un dashboard pour analyse de l'évolution annuelle des tendances\nNotes, nouveaux users et films, note moyenne, \nPSI des genres et évolution de la part des genres",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Notations annuelles",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n  period_value || '' AS annee,\r\n  metric_value\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'yearly'\r\n  AND metric_name = 'nb_notes'\r\n  AND metric_value > 0\r\n  AND period_value > '1995'\r\nORDER BY annee;"
    }
   ]
  },
  {
   "title": "New users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n  period_value || '' AS annee,\r\n  metric_value\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'yearly'\r\n  AND metric_name = 'nb_new_users'\r\n  AND metric_value > 0\r\n  AND period_value > '1995'\r\nORDER BY annee;"
    }
   ]
  },
  {
   "title": "Nb new movies",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT metric_value, \r\n  period_value || '' AS annee\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'yearly'\r\n  AND metric_value > 0\r\n  AND period_value > '1996'\r\n  AND metric_name like 'nb_new_movies'\r\nORDER BY annee;"
    }
   ]
  },
  {
   "title": "avg_rating",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT metric_value, \r\n  period_value || '' AS annee\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'yearly'\r\n  AND metric_value > 0\r\n  AND period_value > '1995'\r\n  AND metric_name='avg_rating'\r\nORDER BY annee;"
    }
   ]
  },
  {
   "title": "Indicateur de Stabilité Genre",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT metric_value, \r\n  period_value || '' AS annee\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'yearly'\r\n  AND metric_value > 0\r\n  AND period_value > '1996'\r\n  AND metric_name like 'psi_genre%'\r\nORDER BY annee;"
    }
   ]
  },
  {
   "title": "Evolution de la part de romance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT metric_value, metric_name,\r\n  period_value::text AS annee\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'yearly'\r\n  AND metric_value > 0\r\n  AND period_value > '1995'\r\n  and metric_name='pct_genre_Romance'\r\nORDER BY annee;"
    }
   ]
  }
 ]
}