{
 "title": "Monitoring quotidien",
 "description": "Initialisation d'un monitoring quotidien : nombre de notes et users, nouveaux users et nouveaux films notés",
 "time": { "from": "now-4070d", "to": "now-4020d" },
 "panels": [
  {
   "title": "Nombre de notes par jour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n    period_value::date AS date,\r\n    metric_value AS nb_notes\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'daily'\r\n  AND metric_name = 'nb_notes'\r\n  and metric_value>0\r\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Nouveaux films par jour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n    period_value::date AS date,\r\n    metric_value AS nb_new_users\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'daily'\r\n  AND metric_name = 'nb_new_movies'\r\n  and metric_value>0\r\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Nb users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n    period_value::date AS date,\r\n    metric_value AS nb_users\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'daily'\r\n  AND metric_name = 'nb_users'\r\n  and metric_value>0\r\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Nb new users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "SELECT\r\n    period_value::date AS date,\r\n    metric_value AS nb_users\r\nFROM raw.monitoring_metrics\r\nWHERE period_type = 'daily'\r\n  AND metric_name = 'nb_new_users'\r\n  and metric_value>0\r\nORDER BY date;"
    }
   ]
  }
 ]
}