{
 "title": "Pipeline health",
 "description": "Suivi des runs ingestion et training",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ingestions runs - raw_ratings_injected",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_run_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    rows_ratings_injected\r\n  FROM raw.ingestion_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_run_per_day\r\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Ingestions runs - raw_movies_injectd",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_run_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    rows_movies_injected\r\n  FROM raw.ingestion_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_run_per_day\r\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Ingestions runs Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_run_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    duration_sec\r\n  FROM raw.ingestion_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_run_per_day\r\nORDER BY day DESC;"
    }
   ]
  },
  {
   "title": "Training runs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "movie_reco",
     "rawSql": "WITH last_training_per_day AS (\r\n  SELECT DISTINCT ON (DATE(started_at))\r\n    DATE(started_at) AS day,\r\n    status,\r\n    duration_sec,\r\n    error_message\r\n  FROM raw.training_run_log\r\n  ORDER BY DATE(started_at), started_at DESC\r\n)\r\nSELECT *\r\nFROM last_training_per_day\r\nORDER BY day DESC;"
    }
   ]
  }
 ]
}